version: '2'
services:
  web-server:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: ['npm', 'run-script', 'start:dev']
    depends_on:
      - mongo
  nginx:
    build: ./nginx
    depends_on:
      - web-server
    links:
      - web-server:web-server
    ports:
      - "80:80"
      - "443:443"
    restart: always
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
